### ISSUE TITLE
Tarea Finde

### ISSUE THREAD

**Issue by olmocorell** [JaimeSanz28/Amazon-Leapers#4]
Las dos issues anteriores completadas y cerradas.... dataset terminado para poder entrenar este fin de semana.

**Comment by JaimeSanzzz** [comment]
asi es asi es!!!! hoy si Dios quiere termino el dia con un dataset super guapooooooooooooo! 🤓

![image](https://user-images.githubusercontent.com/64034336/88375506-fc9d1780-cd9b-11ea-9006-1920527a9367.png)
