### ISSUE TITLE
investigación/red neuronal/ML

### ISSUE THREAD

**Issue by olmocorell** [JaimeSanz28/Amazon-Leapers#5]
Decidir qué vas a usar para clasificar, si la red neuronal o un algoritmo de ML.
Puedes agendar un calendly con Marc para que te eche una mano con la decisión y te oriente.
Pero vamos, que tendrás que tirar de KERAS, así que échale un vistazo a la documentación porque entrenar una red neuronal tiene miguita ¿vale?
https://medium.com/gradientcrescent/urban-sound-classification-using-convolutional-neural-networks-with-keras-theory-and-486e92785df4

**Comment by JaimeSanzzz** [comment]
ok perfe, tengo una reunion con el a las 16.30. Me leo bien la docu antes y veo que opina el que es mejor. salu2
