### ISSUE TITLE
[feedback - meme]

### ISSUE THREAD

**Issue by ferrero-felipe** [JaimeSanz28/Amazon-Leapers#6]
MI REEEEEEEY,
Muy buen trabajo, Jaime.
Ha quedado genial y seguramente te has entretenido haciendolo. Y lo más importante, has aprendido un monton.
Igualmente hay que darte las gracias por estar siempre de buen rollo, fabricando memes geniales. Y eso es super importante para el ambiente de trabajo..
Eres un maquina

![image](https://user-images.githubusercontent.com/52798316/89026168-7c8d2980-d328-11ea-8965-73a64d48fb03.png)

**Comment by JaimeSanzzz** [comment]
Felipito tio que decirte.. mil gracias por todo de todo corazón. Ha sido un verdadero placer tenerte de TA y compartir contigo la experiencia que es Ironhack durante todas estas semanas de desenfreno y de no parar de aprender. Gracias a ti también por el buen rollo, las risas y tu gran paciencia con todos nosotros!! 
Ya nos veremos, hasta entonces, un fuerte abrazo amigo! ❤️
