### ISSUE TITLE
[feedback-ras]

### ISSUE THREAD

**Issue by olmocorell** [JaimeSanz28/Amazon-Leapers#7]
Gracias Jaime, por no haber tirado la toalla, por el bootcamp, por tus ganas de seguir avanzando y llegar hasta el final.
Por todo lo que te has peleado con los audios.
Por tener un objetivo desde los primeros días y luchar por él. 
Me encantaría que echaras un rato para arreglar lo que te falta y metieras la foto, datos y la ubicación. 
Como te he dicho, pide la licencia y consigue todo el dataset. 
Estoy muy orgullosa de ti.

![IMG_5107 2](https://user-images.githubusercontent.com/57899051/89026534-2e2c5a80-d329-11ea-95b4-59d0970c1282.JPG)

**Comment by JaimeSanzzz** [comment]
Ras, mil gracias a ti por haber confiado siempre en mí, sin ti jamás lo habría logrado. Ha sido un verdadero placer tenerte como TA durante estas 8 intensas pero muy satisfactorias semanas. Has estado siempre ahí para todos y para cualquier tema, ya fuese de programación o no, y sobretodo, lo más importante es que siempre has estado de súper buen rollo y viviéndolo todo con una pasión contagiosa. Muchas gracias por eso, eres un persona genial, da gusto lo mucho que te encanta lo que haces. Completar el bootcamp (además habiéndolo completado bastante bien en mi poca humilde opinión) es algo que me llena el ego enormemente, no obstante, se me han quedado algunas cosillas pendientes cómo pueden ser ganar la competición de los diamantes o el hacha. No tengo tiempo, por tanto, para levantar el pie del acelerador, ahora es mi turno de adelantarme a mí mismo y no parar de mejorar. Un millón de gracias por haberme ayudado a poner la primera piedrecita en mi formación como Data Analyst, desde aquí ya solo para arriba. Espero que entremos en un círculo virtuoso de recomendarnos libros y demás cosillas para avanzar.
Ya nos veremos, un muy fuerte abrazo de tu hijo favorito ❤️
