### ISSUE TITLE
[feedback-marc]

### ISSUE THREAD

**Issue by boyander** [JaimeSanz28/Amazon-Leapers#8]
Jaime!

Bueno, cuando explicaste de que iba tu proyecto casi no me lo podía creer. Pero te ha salido a las mil maravillas, enhorabuena!

Gracias por cuidar de #datamad0620 siempre con tus memes ultra currados :)

Nos vemos pronto crack! 
Abrazoos!!

MP

![](https://i.pinimg.com/originals/43/9e/a3/439ea38dd7ebe14b297c6cf3c6c5d4ad.gif)

**Comment by JaimeSanzzz** [comment]
Muchas gracias Marc!
jaja si no te hubiese parecido algo loco yo jamás habría estado contento con la idea.. para eso es al fin y al cabo el proyecto final, no? para sorprendernos a nosotros mismos.
Ya nos veremos, disfruta de las vacaciones!! Un fuerte abrazo y mil gracias por estas 8 geniales semanas ❤️
